---
version: "3.7"

services:
  nginx:
    build:
      context: "containers/nginx"
    environment:
      APP_HOST: app
      APP_PORT: 4567
      APP_NAME: test_app
      BLACKHOLE_PATH: "/blackholes"
    ports:
    - target: 80
      published: 3000
      protocol: tcp
    volumes:
      - "blackholes:/blackholes"

  app:
    build: "containers/webapp"
    ports:
    - target: 4567
      published: 4567
      protocol: tcp
    tty: true
    stdin_open: true
    volumes:
      - "blackholes:/home/app-runner/app/blackholes"
volumes:
  blackholes:
